# Generated by Django 4.1.3 on 2022-12-14 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownersequity',
            old_name='widthdraw',
            new_name='withdraw',
        ),
    ]
