# Generated by Django 4.1.3 on 2022-12-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0004_investment_withdraw_remove_owner_ownership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
