# Generated by Django 4.1.3 on 2022-12-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0005_withdraw_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='comment',
            new_name='detail',
        ),
        migrations.AddField(
            model_name='investment',
            name='detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
