# Generated by Django 4.1.3 on 2022-12-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0006_rename_comment_withdraw_detail_investment_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
    ]
