# Generated by Django 4.1.3 on 2023-01-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0007_remove_owner_address_remove_owner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='মোবাইল'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='নাম'),
        ),
    ]
