# Generated by Django 4.1.3 on 2023-01-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0008_alter_owner_mobile_alter_owner_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='withdraw',
            options={'ordering': ['-date']},
        ),
    ]
