# Generated by Django 4.1.3 on 2023-03-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0010_alter_investment_amount_alter_investment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownersequity',
            name='profit',
            field=models.IntegerField(default=0, verbose_name='মুনাফা'),
        ),
    ]
