# Generated by Django 4.2.3 on 2024-01-27 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0018_alter_ownersequity_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownersequity',
            name='month',
            field=models.IntegerField(choices=[(1, 'জানুয়ারি'), (2, 'ফেব্রুয়ারি'), (3, 'মার্চ'), (4, 'এপ্রিল'), (5, 'মে'), (6, 'জুন'), (7, 'জুলাই'), (8, 'আগস্ট'), (9, 'সেপ্টেম্বর'), (10, 'অক্টোবর'), (11, 'নভেম্বর'), (12, 'ডিসেম্বর')], default=1, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='ownersequity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.owner', verbose_name='অংশীদারের নাম'),
        ),
        migrations.AlterField(
            model_name='ownersequity',
            name='year',
            field=models.IntegerField(choices=[(2022, '২০২২'), (2023, '২০২৩'), (2024, '২০২৪')], default=2024, verbose_name='বছর'),
        ),
    ]
