# Generated by Django 4.2.3 on 2024-08-15 00:48

import Transaction.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0021_alter_ownersequity_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='date',
            field=models.DateField(default=Transaction.functions.next_to_last_balance_date, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateField(default=Transaction.functions.next_to_last_balance_date, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='date',
            field=models.DateField(default=Transaction.functions.next_to_last_balance_date, verbose_name='তারিখ'),
        ),
    ]
