# Generated by Django 5.1.3 on 2024-12-06 02:13

import Transaction.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0028_alter_ownersequity_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=Transaction.functions.next_to_last_balance_date, verbose_name='তারিখ')),
                ('amount', models.FloatField(null=True, verbose_name='পরিমাণ')),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'get_latest_by': ['date'], 'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='ownersequity',
            name='date',
            field=models.DateField(default=Transaction.functions.next_to_last_balance_date, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='ownersequity',
            name='month',
            field=models.IntegerField(default=1, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='ownersequity',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='বছর'),
        ),
    ]
