# Generated by Django 5.1.3 on 2024-12-08 13:15

import Transaction.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0029_profit_alter_investment_options_ownersequity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='date',
            field=models.DateField(default=Transaction.functions.last_balance_date, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateField(default=Transaction.functions.last_balance_date, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='ownersequity',
            name='date',
            field=models.DateField(default=Transaction.functions.last_balance_date, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='date',
            field=models.DateField(default=Transaction.functions.last_balance_date, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='date',
            field=models.DateField(default=Transaction.functions.last_balance_date, verbose_name='তারিখ'),
        ),
    ]
