# Generated by Django 5.1.3 on 2024-12-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0030_alter_fixedasset_date_alter_investment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='profit_share',
            field=models.FloatField(blank=True, default=1, help_text='সম্পূর্ণ অংশ = 1, ৫০% = 0.5 এভাবে নির্ধারণ করতে হবে।', verbose_name='প্রাপ্য লভ্যাংশ'),
        ),
        migrations.AddField(
            model_name='owner',
            name='profit_share_category',
            field=models.CharField(choices=[('equity_rate', 'মালিকানার অংশ হারে'), ('specific_rate', 'নির্দিষ্ট হারে')], default='specific_rate', max_length=20, verbose_name='লভ্যাংশ প্রাপ্তির ধরণ'),
        ),
    ]
