# Generated by Django 5.1.3 on 2024-12-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0031_owner_profit_share_owner_profit_share_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='profit',
            field=models.FloatField(blank=True, default=0, verbose_name='প্রাপ্য লভ্যাংশ'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='profit_share',
            field=models.FloatField(blank=True, default=1, help_text='সম্পূর্ণ অংশ = 1, ৫০% = 0.5 এভাবে নির্ধারণ করতে হবে।', verbose_name='প্রাপ্য লভ্যাংশের হার'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='profit_share_category',
            field=models.CharField(choices=[('equity_rate', 'মালিকানার অংশ হারে'), ('specific_rate', 'নির্দিষ্ট হারে'), ('specific_profit', 'নির্দিষ্ট লভ্যাংশ')], default='specific_rate', max_length=20, verbose_name='লভ্যাংশ প্রাপ্তির ধরণ'),
        ),
    ]
