# Generated by Django 4.2.17 on 2024-12-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0032_owner_profit_alter_owner_profit_share_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'get_latest_by': ['date_created'], 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ownersequity',
            options={'get_latest_by': ['date'], 'ordering': ['-date']},
        ),
        migrations.RemoveConstraint(
            model_name='ownersequity',
            name='unique_ownersequity',
        ),
    ]
