# Generated by Django 4.2.17 on 2025-01-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0033_alter_owner_options_alter_ownersequity_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ownersequity',
            constraint=models.UniqueConstraint(fields=('date', 'owner'), name='unique_ownersequity'),
        ),
    ]
