# Generated by Django 4.1.3 on 2023-01-20 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
