# Generated by Django 4.2.3 on 2024-09-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'get_latest_by': ['start_date']},
        ),
    ]
