# Generated by Django 4.1.3 on 2022-12-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Company under Group', 'Company under Group')], default=('Individual', 'Individual'), max_length=20, verbose_name='Customer Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.groupofcompany'),
        ),
    ]
