# Generated by Django 4.1.3 on 2022-12-14 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_groupofcompany_alter_customer_cust_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.groupofcompany'),
        ),
    ]
