# Generated by Django 4.1.3 on 2022-12-14 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_customer_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='duecollection',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='duesell',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='groupofcompany',
            options={'ordering': ['name']},
        ),
    ]
