# Generated by Django 4.1.3 on 2022-12-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_customer_default_product_alter_customer_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duecollection',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='duesell',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
