# Generated by Django 4.1.3 on 2022-12-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_duecollection_comment_duesell_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='default_product',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
