# Generated by Django 4.1.3 on 2022-12-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['cust_type', 'group', 'name']},
        ),
    ]
