# Generated by Django 4.1.3 on 2023-01-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_remove_purchase_comment_remove_sell_comment_and_more'),
        ('Customer', '0008_alter_customer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duecollection',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='duesell',
            name='comment',
        ),
        migrations.AddField(
            model_name='duesell',
            name='rate',
            field=models.FloatField(default=0.0, verbose_name='দর'),
        ),
        migrations.AlterField(
            model_name='duecollection',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='টাকা'),
        ),
        migrations.AlterField(
            model_name='duecollection',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customer', verbose_name='ক্রেতা'),
        ),
        migrations.AlterField(
            model_name='duesell',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='মোট'),
        ),
        migrations.AlterField(
            model_name='duesell',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customer', verbose_name='ক্রেতা'),
        ),
        migrations.AlterField(
            model_name='duesell',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product', verbose_name='মাল'),
        ),
        migrations.AlterField(
            model_name='duesell',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='পরিমাণ'),
        ),
    ]
