# Generated by Django 4.1.3 on 2023-01-05 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_remove_duecollection_comment_remove_duesell_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_type',
            field=models.CharField(choices=[('Individual', 'একক প্রতিষ্ঠান'), ('Group', 'গ্রুপ')], default=('Individual', 'একক প্রতিষ্ঠান'), max_length=20, verbose_name='ধরণ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.groupofcompany', verbose_name='গ্রুপ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='মোবাইল'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='নাম'),
        ),
        migrations.AlterField(
            model_name='groupofcompany',
            name='name',
            field=models.CharField(max_length=255, verbose_name='নাম'),
        ),
    ]
