# Generated by Django 4.1.3 on 2023-01-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_alter_customer_cust_type_alter_customer_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['cust_type', 'group', 'serial']},
        ),
        migrations.AddField(
            model_name='customer',
            name='serial',
            field=models.SmallIntegerField(default=0, verbose_name='ক্রম'),
        ),
        migrations.AddField(
            model_name='customer',
            name='short_name',
            field=models.CharField(default='', max_length=25, verbose_name='সংক্ষিপ্ত নাম'),
            preserve_default=False,
        ),
    ]
