# Generated by Django 4.1.3 on 2023-01-22 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_alter_customer_options_customer_serial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['cust_type', 'group', 'serial', 'name']},
        ),
        migrations.AlterField(
            model_name='duecollection',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='duesell',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='তারিখ'),
        ),
    ]
