# Generated by Django 4.1.3 on 2023-01-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_alter_duecollection_options_alter_duesell_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='short_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='সংক্ষিপ্ত নাম'),
        ),
    ]
