# Generated by Django 4.1.3 on 2023-02-06 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0025_alter_product_options_alter_purchase_quantity_and_more'),
        ('Customer', '0015_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duesell',
            name='product',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product', verbose_name='মাল'),
        ),
        migrations.AlterField(
            model_name='duesell',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='পরিমাণ'),
        ),
    ]
