# Generated by Django 4.1.3 on 2023-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0018_alter_customer_options_customer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_type',
            field=models.CharField(choices=[('Individual', 'একক প্রতিষ্ঠান'), ('Group', 'গ্রুপ')], default='Individual', max_length=20, verbose_name='ধরণ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'সক্রিয়'), ('inactive', 'নিষ্ক্রিয়')], default='active', max_length=20, verbose_name='অবস্থা'),
        ),
    ]
