# Generated by Django 4.1.3 on 2023-03-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0019_alter_customer_cust_type_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecollection',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='টাকা'),
        ),
        migrations.AlterField(
            model_name='duesell',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='মোট'),
        ),
    ]
