# Generated by Django 4.1.3 on 2023-03-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0020_alter_duecollection_amount_alter_duesell_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['active', 'cust_type', 'group', 'serial', 'name']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='groupofcompany',
            name='status',
        ),
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='সক্রিয়'),
        ),
        migrations.AddField(
            model_name='groupofcompany',
            name='active',
            field=models.BooleanField(default=True, verbose_name='সক্রিয়'),
        ),
        migrations.AlterField(
            model_name='duecollection',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customer', verbose_name='ক্রেতা'),
        ),
        migrations.AlterField(
            model_name='duesell',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customer', verbose_name='ক্রেতা'),
        ),
    ]
