# Generated by Django 4.1.3 on 2023-03-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0021_alter_customer_options_remove_customer_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-active', 'cust_type', 'group', 'serial', 'name']},
        ),
    ]
