# Generated by Django 4.2.3 on 2023-07-15 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0028_remove_product_purchase_rate_and_more'),
        ('Customer', '0022_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duesell',
            name='product',
            field=models.ForeignKey(default=1, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product', verbose_name='মাল'),
        ),
    ]
