# Generated by Django 4.2.17 on 2025-01-13 15:17

import Transaction.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0035_consumestock_excess_initialstock_purchaserate_and_more'),
        ('Customer', '0024_rename_amount_to_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'get_latest_by': ['date_created'], 'ordering': ['-active', 'cust_type', 'group', 'serial', 'name']},
        ),
        migrations.AlterModelOptions(
            name='duecollection',
            options={'get_latest_by': ['date'], 'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='duesell',
            options={'get_latest_by': ['date'], 'ordering': ['-date', 'customer', 'product__category', 'product__name']},
        ),
        migrations.AlterModelOptions(
            name='groupofcompany',
            options={'ordering': ['serial']},
        ),
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateField(default=Transaction.functions.last_balance_date),
        ),
        migrations.AddField(
            model_name='duesell',
            name='sell',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.sell', verbose_name='বিক্রয়'),
        ),
        migrations.AddField(
            model_name='duesell',
            name='selling_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.sellingrate'),
        ),
        migrations.AddField(
            model_name='groupofcompany',
            name='date_created',
            field=models.DateField(default=Transaction.functions.last_balance_date),
        ),
        migrations.AddField(
            model_name='groupofcompany',
            name='serial',
            field=models.SmallIntegerField(default=0, verbose_name='ক্রম'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='serial',
            field=models.SmallIntegerField(default=0, verbose_name='ক্রম'),
        ),
        migrations.AlterField(
            model_name='duecollection',
            name='amount',
            field=models.FloatField(null=True, verbose_name='টাকা'),
        ),
        migrations.AlterField(
            model_name='duecollection',
            name='date',
            field=models.DateField(default=Transaction.functions.last_balance_date, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='duesell',
            name='date',
            field=models.DateField(default=Transaction.functions.last_balance_date, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='duesell',
            name='price',
            field=models.FloatField(null=True, verbose_name='মোট'),
        ),
        migrations.CreateModel(
            name='GroupofCompanyDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=Transaction.functions.last_balance_date, verbose_name='তারিখ')),
                ('amount', models.FloatField(null=True, verbose_name='পরিমাণ')),
                ('bad_debt', models.BooleanField(default=False, verbose_name='অনিশ্চিত')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.groupofcompany', verbose_name='ক্রেতা')),
            ],
            options={
                'ordering': ['-date', 'customer__serial'],
                'get_latest_by': ['date', 'customer__serial'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=Transaction.functions.last_balance_date, verbose_name='তারিখ')),
                ('amount', models.FloatField(null=True, verbose_name='পরিমাণ')),
                ('bad_debt', models.BooleanField(default=False, verbose_name='অনিশ্চিত')),
                ('customer', models.ForeignKey(limit_choices_to={'cust_type': 'Individual'}, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='ক্রেতা')),
            ],
            options={
                'ordering': ['-date', 'customer__serial'],
                'get_latest_by': ['date', 'customer__serial'],
                'abstract': False,
            },
        ),
    ]
