# Generated by Django 4.1.3 on 2022-12-03 05:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='From Date')),
                ('start_time', models.TimeField(default=datetime.datetime.now, verbose_name='From Time')),
                ('rate', models.FloatField(verbose_name='Rate/Ltr (Tk)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.FloatField(verbose_name='Quantity (Ltr)')),
                ('amount', models.FloatField(verbose_name='Amount (TK)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('rate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.sellingrate')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.FloatField(verbose_name='Quantity (Ltr)')),
                ('rate', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(verbose_name='Amount (TK)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
