# Generated by Django 4.1.3 on 2022-12-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_sellingrate_sell_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='rate',
        ),
    ]
