# Generated by Django 4.1.3 on 2022-12-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_purchase_product_alter_sell_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='sellingrate',
            options={'ordering': ['start_date', 'start_time']},
        ),
        migrations.AddField(
            model_name='purchase',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
