# Generated by Django 4.1.3 on 2022-12-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_purchase_options_alter_sell_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Loose', 'খুচরা'), ('Pack', 'প্যাক')], default=('Loose', 'খুচরা'), max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Liter', 'লিটার'), ('Piece', 'টি')], default=('Liter', 'লিটার'), max_length=20),
        ),
    ]
