# Generated by Django 4.1.3 on 2022-12-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_product_capacity_product_purchase_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_rate',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_rate',
            field=models.FloatField(default=None),
        ),
    ]
