# Generated by Django 4.1.3 on 2022-12-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_product_capacity_alter_product_purchase_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ব্র্যান্ড'),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='পরিমান (লিটার)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='মালের নাম'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_rate',
            field=models.FloatField(default=None, verbose_name='একক প্রতি ক্রয়মুল্য'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_rate',
            field=models.FloatField(default=None, verbose_name='একক প্রতি বিক্রয়মুল্য'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Loose', 'লুস'), ('Pack', 'প্যাক')], default=('Loose', 'লুস'), max_length=20, verbose_name='ধরন'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Liter', 'লিটার'), ('Piece', 'পিস ')], default=('Liter', 'লিটার'), max_length=20, verbose_name='একক'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(verbose_name='Amount (TK)'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='amount',
            field=models.IntegerField(verbose_name='Amount (TK)'),
        ),
    ]
