# Generated by Django 4.1.3 on 2022-12-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_product_brand_alter_product_capacity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellingRate',
        ),
    ]
