# Generated by Django 4.1.3 on 2023-01-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_delete_sellingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity'),
        ),
    ]
