# Generated by Django 4.1.3 on 2023-01-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_purchase_rate_alter_purchase_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='comment',
        ),
        migrations.AddField(
            model_name='sell',
            name='rate',
            field=models.FloatField(default=0.0, verbose_name='দর'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(default=0.0, verbose_name='মোট'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product', verbose_name='মাল'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='rate',
            field=models.FloatField(default=0.0, verbose_name='দর'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='amount',
            field=models.IntegerField(default=0.0, verbose_name='মোট'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product', verbose_name='মাল'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='পরিমাণ'),
        ),
    ]
