# Generated by Django 4.1.3 on 2023-01-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_remove_purchase_comment_remove_sell_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='পরিমান'),
        ),
    ]
