# Generated by Django 4.1.3 on 2023-01-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_remove_product_unit_alter_product_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='মালের নাম')),
            ],
        ),
    ]
