# Generated by Django 4.1.3 on 2023-01-06 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_productgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['group']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Product.productgroup', verbose_name='আইটেম'),
        ),
    ]
