# Generated by Django 4.1.3 on 2023-01-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_alter_product_options_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['item']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='group',
            new_name='item',
        ),
    ]
