# Generated by Django 4.1.3 on 2023-01-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_product_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
    ]
