# Generated by Django 4.1.3 on 2023-01-14 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_alter_product_options_rename_group_product_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['item__name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Product.productgroup', verbose_name='আইটেম'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Loose', 'লুস'), ('Extra', 'এক্স'), ('Pack', 'প্যাক')], default=('Pack', 'প্যাক'), max_length=20, verbose_name='ধরন'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='মাল'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sell',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='মাল'),
            preserve_default=False,
        ),
    ]
