# Generated by Django 4.1.3 on 2023-01-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_alter_product_options_alter_product_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_name',
            field=models.CharField(max_length=10, null=True, verbose_name='মালের সংক্ষপ্ত নাম'),
        ),
    ]
