# Generated by Django 4.1.3 on 2023-01-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_product_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_name',
            field=models.CharField(default=0, max_length=10, verbose_name='মালের সংক্ষপ্ত নাম'),
            preserve_default=False,
        ),
    ]
