# Generated by Django 4.1.3 on 2023-01-22 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_alter_product_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='মালের সংক্ষিপ্ত নাম'),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='তারিখ')),
                ('source', models.CharField(choices=[('0', 'প্রারম্ভিক'), ('1', 'ক্রয়'), ('2', 'বিক্রয়'), ('3', 'নজেল ত্রুটি')], max_length=20, verbose_name='উৎস')),
                ('amount', models.FloatField(default=0, verbose_name='পরিমাণ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product', verbose_name='মাল')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
