# Generated by Django 4.1.3 on 2023-01-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_alter_product_short_name_storage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
