# Generated by Django 4.1.3 on 2023-01-27 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_alter_product_type_storagereading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='storagereading',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='মালের নাম'),
        ),
        migrations.AddField(
            model_name='product',
            name='need_rescale',
            field=models.BooleanField(default=False, verbose_name='মজুদ মাপতে হয়'),
        ),
        migrations.AlterField(
            model_name='storagereading',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='storagereading',
            name='product',
            field=models.ForeignKey(limit_choices_to={'type': 'Loose'}, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='মাল'),
        ),
    ]
