# Generated by Django 4.1.3 on 2023-01-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_alter_product_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagereading',
            name='product',
            field=models.ForeignKey(limit_choices_to={'need_rescale': True}, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='মাল'),
        ),
        migrations.AddConstraint(
            model_name='storagereading',
            constraint=models.UniqueConstraint(fields=('date', 'product'), name='unique_storage_reading'),
        ),
    ]
