# Generated by Django 4.1.3 on 2023-02-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0024_delete_productgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['type', 'name', 'capacity']},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='পরিমাণ'),
        ),
    ]
