# Generated by Django 4.1.3 on 2023-03-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0025_alter_product_options_alter_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='মোট'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='মোট'),
        ),
        migrations.AlterField(
            model_name='storagereading',
            name='tank_deep',
            field=models.FloatField(null=True, verbose_name='ট্যাংক ডিপ'),
        ),
    ]
