# Generated by Django 4.1.3 on 2023-03-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0026_alter_purchase_amount_alter_sell_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='সক্রিয়'),
        ),
    ]
