# Generated by Django 4.2.3 on 2023-07-15 02:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0027_product_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_rate',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='মাল'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='product',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='মাল'),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='কার্যকর (হইতে)')),
                ('purchase_rate', models.FloatField(default=None, verbose_name='একক প্রতি ক্রয়মুল্য')),
                ('selling_rate', models.FloatField(default=None, verbose_name='একক প্রতি বিক্রয়মুল্য')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='মালের নাম')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
