# Generated by Django 4.2.3 on 2023-07-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0029_alter_product_capacity_alter_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='purchase_rate',
            field=models.FloatField(default=0, verbose_name='একক প্রতি ক্রয়মুল্য'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='selling_rate',
            field=models.FloatField(default=0, verbose_name='একক প্রতি বিক্রয়মুল্য'),
        ),
    ]
