# Generated by Django 4.2.3 on 2023-10-25 08:48

import Transaction.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0030_alter_rate_purchase_rate_alter_rate_selling_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=Transaction.functions.next_to_last_balance_date),
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(default=Transaction.functions.next_to_last_balance_date, help_text='YYYY-MM-DD', verbose_name='কার্যকরের তারিখ (হইতে)'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(default=Transaction.functions.next_to_last_balance_date),
        ),
        migrations.AlterField(
            model_name='storagereading',
            name='date',
            field=models.DateField(default=Transaction.functions.last_balance_date, verbose_name='তারিখ'),
        ),
    ]
