# Generated by Django 4.2.3 on 2024-08-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0032_alter_rate_options_changedproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangedProduct',
        ),
    ]
