# Generated by Django 4.2.17 on 2025-01-13 15:17

import Transaction.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0034_rename_amount_to_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=Transaction.functions.last_balance_date)),
                ('quantity', models.FloatField(default=0)),
                ('profit_rate', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Excess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=Transaction.functions.last_balance_date)),
                ('quantity', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InitialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=Transaction.functions.last_balance_date)),
                ('quantity', models.FloatField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-date', 'product__name'],
                'get_latest_by': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=Transaction.functions.last_balance_date, verbose_name='কার্যকরের তারিখ (হইতে)')),
                ('amount', models.FloatField(default=0, verbose_name='একক প্রতি মুল্য')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseRateVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='নাম')),
                ('normal', models.BooleanField(default=False, verbose_name='স্বাভাবিক দর')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=Transaction.functions.last_balance_date, verbose_name='কার্যকরের তারিখ (হইতে)')),
                ('amount', models.FloatField(default=0, verbose_name='একক প্রতি মুল্য')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellingRateVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='নাম')),
                ('normal', models.BooleanField(default=False, verbose_name='স্বাভাবিক দর')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=Transaction.functions.last_balance_date)),
                ('quantity', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=Transaction.functions.last_balance_date)),
                ('stock_in_type', models.CharField(choices=[('initial_stock', 'প্রারম্ভিক মজুদ (হিসাব শুরুর তারিখের)'), ('purchase', 'ক্রয়')], max_length=50)),
                ('consumable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date', '-stock_in_type'],
                'get_latest_by': ['date', 'stock_in_type'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-active', 'category', 'name', 'capacity']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'get_latest_by': 'date', 'ordering': ['-date', 'product__category', 'product__name']},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={'get_latest_by': 'date', 'ordering': ['-date', 'product__category', 'product__name']},
        ),
        migrations.AlterModelOptions(
            name='storagereading',
            options={'get_latest_by': 'date', 'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='need_rescale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fuel', 'জ্বালানী'), ('loose_lubricant', 'লুব্রিকেন্ট (লুস)'), ('lubricant', 'লুব্রিকেন্ট'), ('others', 'অন্যান্য')], default='lubricant', max_length=20, verbose_name='ধরন'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateField(default=Transaction.functions.last_balance_date),
        ),
        migrations.AddField(
            model_name='product',
            name='packaged',
            field=models.BooleanField(default=True, verbose_name='মোড়কজাত'),
        ),
        migrations.AddField(
            model_name='storagereading',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='মালের নাম'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=Transaction.functions.last_balance_date),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(default=Transaction.functions.last_balance_date, help_text='YYYY-MM-DD', verbose_name='কার্যকরের তারিখ (হইতে)'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(default=Transaction.functions.last_balance_date),
        ),
        migrations.AlterField(
            model_name='sell',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='storagereading',
            name='lorry_load',
            field=models.FloatField(default=0, verbose_name='গাড়ীতে লোডকৃত'),
        ),
        migrations.AlterField(
            model_name='storagereading',
            name='product',
            field=models.ForeignKey(limit_choices_to={'category': 'fuel'}, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='মাল'),
        ),
        migrations.AlterField(
            model_name='storagereading',
            name='tank_deep',
            field=models.FloatField(null=True, verbose_name='ট্যাংক-এ অবশিষ্ট'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['product', 'date'], name='Product_pur_product_43ec21_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['product'], name='Product_pur_product_e0f45a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['price'], name='Product_pur_price_69541f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['quantity'], name='Product_pur_quantit_324781_idx'),
        ),
        migrations.AddIndex(
            model_name='sell',
            index=models.Index(fields=['product', 'date'], name='Product_sel_product_34756d_idx'),
        ),
        migrations.AddIndex(
            model_name='sell',
            index=models.Index(fields=['product'], name='Product_sel_product_87ee6d_idx'),
        ),
        migrations.AddIndex(
            model_name='sell',
            index=models.Index(fields=['price'], name='Product_sel_price_6ee22c_idx'),
        ),
        migrations.AddIndex(
            model_name='sell',
            index=models.Index(fields=['quantity'], name='Product_sel_quantit_639e8c_idx'),
        ),
        migrations.AddField(
            model_name='stock',
            name='initial_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.initialstock'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.purchase'),
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.purchaserate'),
        ),
        migrations.AddField(
            model_name='shortage',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.stock'),
        ),
        migrations.AddField(
            model_name='shortage',
            name='storage_reading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.storagereading'),
        ),
        migrations.AddField(
            model_name='sellingrate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='মালের নাম'),
        ),
        migrations.AddField(
            model_name='sellingrate',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.sellingratevariant', verbose_name='ধরন'),
        ),
        migrations.AddField(
            model_name='purchaserate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='মালের নাম'),
        ),
        migrations.AddField(
            model_name='purchaserate',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.purchaseratevariant', verbose_name='ধরন'),
        ),
        migrations.AddField(
            model_name='initialstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
        migrations.AddField(
            model_name='initialstock',
            name='purchase_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.purchaserate'),
        ),
        migrations.AddField(
            model_name='excess',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.stock'),
        ),
        migrations.AddField(
            model_name='excess',
            name='storage_reading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.storagereading'),
        ),
        migrations.AddField(
            model_name='consumestock',
            name='sell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.sell'),
        ),
        migrations.AddField(
            model_name='consumestock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.stock'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.purchaserate', verbose_name='দর'),
        ),
        migrations.AddField(
            model_name='sell',
            name='selling_rate',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.sellingrate', verbose_name='দর'),
        ),
        migrations.AddField(
            model_name='storagereading',
            name='purchase_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.purchaserate'),
        ),
        migrations.AddIndex(
            model_name='sellingrate',
            index=models.Index(fields=['product', 'variant'], name='Product_sel_product_8c15cf_idx'),
        ),
        migrations.AddIndex(
            model_name='sellingrate',
            index=models.Index(fields=['date'], name='Product_sel_date_21d40a_idx'),
        ),
        migrations.AddIndex(
            model_name='sellingrate',
            index=models.Index(fields=['amount'], name='Product_sel_amount_14bb83_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserate',
            index=models.Index(fields=['product', 'variant'], name='Product_pur_product_d814bc_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserate',
            index=models.Index(fields=['date'], name='Product_pur_date_80dcf5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserate',
            index=models.Index(fields=['amount'], name='Product_pur_amount_cf104b_idx'),
        ),
    ]
