# Generated by Django 4.2.3 on 2024-09-18 13:35

import Transaction.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0035_alter_product_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-active', 'type', 'name', 'capacity']},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Product', max_length=100, verbose_name='মালের নাম'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='short_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='মালের সংক্ষিপ্ত নাম'),
        ),
        migrations.CreateModel(
            name='SellingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('date', models.DateField(default=Transaction.functions.next_to_last_balance_date, help_text='YYYY-MM-DD', verbose_name='কার্যকরের তারিখ (হইতে)')),
                ('amount', models.FloatField(default=0, verbose_name='একক প্রতি বিক্রয়মুল্য')),
                ('default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='মালের নাম')),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
    ]
