# Generated by Django 4.1.3 on 2023-01-15 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_alter_customer_cust_type_alter_customer_group_and_more'),
        ('Ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupofcompanybalance',
            options={'ordering': ['-year', 'month', 'customer']},
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'cust_type': 'Individual'}, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='পার্টি'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='month',
            field=models.CharField(choices=[('1', 'জানুয়ারি'), ('2', 'ফেব্রুয়ারি'), ('3', 'মার্চ'), ('4', 'এপ্রিল'), ('5', 'মে'), ('6', 'জুন'), ('7', 'জুলাই'), ('8', 'আগস্ট'), ('9', 'সেপ্টেম্বর'), ('10', 'অক্টোবর'), ('11', 'নভেম্বর'), ('12', 'ডিসেম্বর')], default=12, max_length=20, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='year',
            field=models.IntegerField(choices=[(2022, '২০২২')], default=2022, verbose_name='বছর'),
        ),
        migrations.AlterField(
            model_name='groupofcompanybalance',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='পরিমাণ (টাকা)'),
        ),
        migrations.AlterField(
            model_name='groupofcompanybalance',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.groupofcompany', verbose_name='পার্টি'),
        ),
        migrations.AlterField(
            model_name='groupofcompanybalance',
            name='month',
            field=models.CharField(choices=[('1', 'জানুয়ারি'), ('2', 'ফেব্রুয়ারি'), ('3', 'মার্চ'), ('4', 'এপ্রিল'), ('5', 'মে'), ('6', 'জুন'), ('7', 'জুলাই'), ('8', 'আগস্ট'), ('9', 'সেপ্টেম্বর'), ('10', 'অক্টোবর'), ('11', 'নভেম্বর'), ('12', 'ডিসেম্বর')], max_length=20, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='groupofcompanybalance',
            name='year',
            field=models.IntegerField(choices=[(2022, '২০২২')], default=2022, verbose_name='বছর'),
        ),
    ]
