# Generated by Django 4.1.3 on 2023-01-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_delete_storage'),
        ('Ledger', '0002_alter_groupofcompanybalance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'জানুয়ারি'), ('2', 'ফেব্রুয়ারি'), ('3', 'মার্চ'), ('4', 'এপ্রিল'), ('5', 'মে'), ('6', 'জুন'), ('7', 'জুলাই'), ('8', 'আগস্ট'), ('9', 'সেপ্টেম্বর'), ('10', 'অক্টোবর'), ('11', 'নভেম্বর'), ('12', 'ডিসেম্বর')], max_length=20, verbose_name='মাস')),
                ('year', models.IntegerField(choices=[(2022, '২০২২')], default=2022, verbose_name='বছর')),
                ('amount', models.FloatField(default=0, verbose_name='পরিমাণ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product', verbose_name='মাল')),
            ],
            options={
                'ordering': ['year', 'month', 'product'],
            },
        ),
    ]
