# Generated by Django 4.1.3 on 2023-01-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0003_storage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerbalance',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterModelOptions(
            name='groupofcompanybalance',
            options={'ordering': ['-year', '-month', 'customer']},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['-year', '-month', 'product']},
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='year',
            field=models.IntegerField(choices=[(2022, '২০২২'), (2023, '২০২৩')], default=2023, verbose_name='বছর'),
        ),
        migrations.AlterField(
            model_name='groupofcompanybalance',
            name='year',
            field=models.IntegerField(choices=[(2022, '২০২২'), (2023, '২০২৩')], default=2023, verbose_name='বছর'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='year',
            field=models.IntegerField(choices=[(2022, '২০২২'), (2023, '২০২৩')], default=2023, verbose_name='বছর'),
        ),
    ]
