# Generated by Django 4.1.3 on 2023-02-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0025_alter_product_options_alter_purchase_quantity_and_more'),
        ('Ledger', '0006_rename_amount_storage_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='price',
            field=models.IntegerField(default=0, verbose_name='ক্রয়মুল্য'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='মাল'),
            preserve_default=False,
        ),
    ]
