# Generated by Django 4.1.3 on 2023-02-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0007_storage_price_alter_storage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbalance',
            name='bad_debt',
            field=models.IntegerField(default=0, verbose_name='অনাদায়ী'),
        ),
        migrations.AddField(
            model_name='groupofcompanybalance',
            name='bad_debt',
            field=models.IntegerField(default=0, verbose_name='অনাদায়ী'),
        ),
    ]
