# Generated by Django 4.1.3 on 2023-02-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0009_remove_customerbalance_bad_debt_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='baddebt',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'customer'), name='unique_baddebt'),
        ),
    ]
