# Generated by Django 4.1.3 on 2023-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0010_baddebt_unique_baddebt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbalance',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='পরিমাণ'),
        ),
    ]
