# Generated by Django 4.1.3 on 2023-03-06 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0020_alter_duecollection_amount_alter_duesell_amount'),
        ('Ledger', '0011_alter_customerbalance_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'জানুয়ারি'), ('2', 'ফেব্রুয়ারি'), ('3', 'মার্চ'), ('4', 'এপ্রিল'), ('5', 'মে'), ('6', 'জুন'), ('7', 'জুলাই'), ('8', 'আগস্ট'), ('9', 'সেপ্টেম্বর'), ('10', 'অক্টোবর'), ('11', 'নভেম্বর'), ('12', 'ডিসেম্বর')], max_length=20, verbose_name='মাস')),
                ('year', models.IntegerField(choices=[(2022, '২০২২'), (2023, '২০২৩')], default=2023, verbose_name='বছর')),
                ('amount', models.IntegerField(null=True, verbose_name='পরিমাণ')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AlterModelOptions(
            name='baddebt',
            options={'ordering': ['-year', 'month', 'customer']},
        ),
        migrations.AlterModelOptions(
            name='customerbalance',
            options={'ordering': ['-year', '-month', 'customer__serial']},
        ),
        migrations.AlterField(
            model_name='baddebt',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='baddebt',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'status': 'active'}, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='পার্টি'),
        ),
        migrations.AlterField(
            model_name='baddebt',
            name='month',
            field=models.CharField(choices=[('1', 'জানুয়ারি'), ('2', 'ফেব্রুয়ারি'), ('3', 'মার্চ'), ('4', 'এপ্রিল'), ('5', 'মে'), ('6', 'জুন'), ('7', 'জুলাই'), ('8', 'আগস্ট'), ('9', 'সেপ্টেম্বর'), ('10', 'অক্টোবর'), ('11', 'নভেম্বর'), ('12', 'ডিসেম্বর')], default=3, max_length=20, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'cust_type': 'Individual', 'status': 'active'}, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='পার্টি'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='month',
            field=models.CharField(choices=[('1', 'জানুয়ারি'), ('2', 'ফেব্রুয়ারি'), ('3', 'মার্চ'), ('4', 'এপ্রিল'), ('5', 'মে'), ('6', 'জুন'), ('7', 'জুলাই'), ('8', 'আগস্ট'), ('9', 'সেপ্টেম্বর'), ('10', 'অক্টোবর'), ('11', 'নভেম্বর'), ('12', 'ডিসেম্বর')], default=2, max_length=20, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='groupofcompanybalance',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='পরিমাণ'),
        ),
        migrations.AddConstraint(
            model_name='profit',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='unique_profit'),
        ),
    ]
