# Generated by Django 4.1.3 on 2023-03-13 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0020_alter_duecollection_amount_alter_duesell_amount'),
        ('Ledger', '0012_profit_alter_baddebt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbalance',
            name='bad_debt',
            field=models.BooleanField(default=False, verbose_name='অনিশ্চিত'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='পার্টি'),
        ),
    ]
