# Generated by Django 4.1.3 on 2023-03-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0015_alter_baddebt_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupofcompanybalance',
            name='bad_debt',
            field=models.BooleanField(default=False, verbose_name='অনিশ্চিত'),
        ),
    ]
