# Generated by Django 4.1.3 on 2023-03-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0021_alter_customer_options_remove_customer_status_and_more'),
        ('Ledger', '0016_groupofcompanybalance_bad_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baddebt',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='পার্টি'),
        ),
    ]
