# Generated by Django 4.1.3 on 2023-03-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0022_alter_customer_options'),
        ('Ledger', '0017_alter_baddebt_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbalance',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'cust_type': 'Individual'}, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='পার্টি'),
        ),
        migrations.DeleteModel(
            name='BadDebt',
        ),
    ]
