# Generated by Django 4.2.3 on 2023-07-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0019_alter_customerbalance_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='amount',
            field=models.FloatField(null=True, verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.FloatField(default=0, verbose_name='ক্রয়মুল্য'),
        ),
    ]
