# Generated by Django 4.2.3 on 2024-01-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0021_alter_customerbalance_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profit',
            options={'get_latest_by': ['-year', '-month'], 'ordering': ['-year', '-month']},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'get_latest_by': ['year', 'month'], 'ordering': ['-year', '-month', 'product']},
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='month',
            field=models.IntegerField(choices=[(1, 'জানুয়ারি'), (2, 'ফেব্রুয়ারি'), (3, 'মার্চ'), (4, 'এপ্রিল'), (5, 'মে'), (6, 'জুন'), (7, 'জুলাই'), (8, 'আগস্ট'), (9, 'সেপ্টেম্বর'), (10, 'অক্টোবর'), (11, 'নভেম্বর'), (12, 'ডিসেম্বর')], default=12, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='year',
            field=models.IntegerField(choices=[(2022, '২০২২'), (2023, '২০২৩'), (2024, '২০২৪')], default=2024, verbose_name='বছর'),
        ),
        migrations.AlterField(
            model_name='groupofcompanybalance',
            name='month',
            field=models.IntegerField(choices=[(1, 'জানুয়ারি'), (2, 'ফেব্রুয়ারি'), (3, 'মার্চ'), (4, 'এপ্রিল'), (5, 'মে'), (6, 'জুন'), (7, 'জুলাই'), (8, 'আগস্ট'), (9, 'সেপ্টেম্বর'), (10, 'অক্টোবর'), (11, 'নভেম্বর'), (12, 'ডিসেম্বর')], default=12, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='groupofcompanybalance',
            name='year',
            field=models.IntegerField(choices=[(2022, '২০২২'), (2023, '২০২৩'), (2024, '২০২৪')], default=2024, verbose_name='বছর'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='month',
            field=models.IntegerField(choices=[(1, 'জানুয়ারি'), (2, 'ফেব্রুয়ারি'), (3, 'মার্চ'), (4, 'এপ্রিল'), (5, 'মে'), (6, 'জুন'), (7, 'জুলাই'), (8, 'আগস্ট'), (9, 'সেপ্টেম্বর'), (10, 'অক্টোবর'), (11, 'নভেম্বর'), (12, 'ডিসেম্বর')], default=12, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='year',
            field=models.IntegerField(choices=[(2022, '২০২২'), (2023, '২০২৩'), (2024, '২০২৪')], default=2024, verbose_name='বছর'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='month',
            field=models.IntegerField(choices=[(1, 'জানুয়ারি'), (2, 'ফেব্রুয়ারি'), (3, 'মার্চ'), (4, 'এপ্রিল'), (5, 'মে'), (6, 'জুন'), (7, 'জুলাই'), (8, 'আগস্ট'), (9, 'সেপ্টেম্বর'), (10, 'অক্টোবর'), (11, 'নভেম্বর'), (12, 'ডিসেম্বর')], default=12, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='year',
            field=models.IntegerField(choices=[(2022, '২০২২'), (2023, '২০২৩'), (2024, '২০২৪')], default=2024, verbose_name='বছর'),
        ),
    ]
