# Generated by Django 4.2.3 on 2024-06-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0022_alter_profit_options_alter_storage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbalance',
            name='month',
            field=models.IntegerField(choices=[(1, 'জানুয়ারি'), (2, 'ফেব্রুয়ারি'), (3, 'মার্চ'), (4, 'এপ্রিল'), (5, 'মে'), (6, 'জুন'), (7, 'জুলাই'), (8, 'আগস্ট'), (9, 'সেপ্টেম্বর'), (10, 'অক্টোবর'), (11, 'নভেম্বর'), (12, 'ডিসেম্বর')], default=5, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='groupofcompanybalance',
            name='month',
            field=models.IntegerField(choices=[(1, 'জানুয়ারি'), (2, 'ফেব্রুয়ারি'), (3, 'মার্চ'), (4, 'এপ্রিল'), (5, 'মে'), (6, 'জুন'), (7, 'জুলাই'), (8, 'আগস্ট'), (9, 'সেপ্টেম্বর'), (10, 'অক্টোবর'), (11, 'নভেম্বর'), (12, 'ডিসেম্বর')], default=5, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='month',
            field=models.IntegerField(choices=[(1, 'জানুয়ারি'), (2, 'ফেব্রুয়ারি'), (3, 'মার্চ'), (4, 'এপ্রিল'), (5, 'মে'), (6, 'জুন'), (7, 'জুলাই'), (8, 'আগস্ট'), (9, 'সেপ্টেম্বর'), (10, 'অক্টোবর'), (11, 'নভেম্বর'), (12, 'ডিসেম্বর')], default=5, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='month',
            field=models.IntegerField(choices=[(1, 'জানুয়ারি'), (2, 'ফেব্রুয়ারি'), (3, 'মার্চ'), (4, 'এপ্রিল'), (5, 'মে'), (6, 'জুন'), (7, 'জুলাই'), (8, 'আগস্ট'), (9, 'সেপ্টেম্বর'), (10, 'অক্টোবর'), (11, 'নভেম্বর'), (12, 'ডিসেম্বর')], default=5, verbose_name='মাস'),
        ),
    ]
