# Generated by Django 4.2.17 on 2025-01-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0035_consumestock_excess_initialstock_purchaserate_and_more'),
        ('Ledger', '0025_alter_customerbalance_month_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profit',
        ),
        migrations.RemoveConstraint(
            model_name='storage',
            name='unique_storage',
        ),
        migrations.AddField(
            model_name='storage',
            name='purchase_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.purchaserate'),
        ),
        migrations.AddField(
            model_name='storage',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='amount',
            field=models.FloatField(null=True, verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='month',
            field=models.IntegerField(choices=[(1, 'জানুয়ারি'), (2, 'ফেব্রুয়ারি'), (3, 'মার্চ'), (4, 'এপ্রিল'), (5, 'মে'), (6, 'জুন'), (7, 'জুলাই'), (8, 'আগস্ট'), (9, 'সেপ্টেম্বর'), (10, 'অক্টোবর'), (11, 'নভেম্বর'), (12, 'ডিসেম্বর')], default=12, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='year',
            field=models.IntegerField(choices=[(2022, '২০২২'), (2023, '২০২৩'), (2024, '২০২৪'), (2025, '২০২৫')], default=2025, verbose_name='বছর'),
        ),
        migrations.AlterField(
            model_name='groupofcompanybalance',
            name='amount',
            field=models.FloatField(null=True, verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='groupofcompanybalance',
            name='month',
            field=models.IntegerField(choices=[(1, 'জানুয়ারি'), (2, 'ফেব্রুয়ারি'), (3, 'মার্চ'), (4, 'এপ্রিল'), (5, 'মে'), (6, 'জুন'), (7, 'জুলাই'), (8, 'আগস্ট'), (9, 'সেপ্টেম্বর'), (10, 'অক্টোবর'), (11, 'নভেম্বর'), (12, 'ডিসেম্বর')], default=12, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='groupofcompanybalance',
            name='year',
            field=models.IntegerField(choices=[(2022, '২০২২'), (2023, '২০২৩'), (2024, '২০২৪'), (2025, '২০২৫')], default=2025, verbose_name='বছর'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='month',
            field=models.IntegerField(choices=[(1, 'জানুয়ারি'), (2, 'ফেব্রুয়ারি'), (3, 'মার্চ'), (4, 'এপ্রিল'), (5, 'মে'), (6, 'জুন'), (7, 'জুলাই'), (8, 'আগস্ট'), (9, 'সেপ্টেম্বর'), (10, 'অক্টোবর'), (11, 'নভেম্বর'), (12, 'ডিসেম্বর')], default=12, verbose_name='মাস'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='year',
            field=models.IntegerField(choices=[(2022, '২০২২'), (2023, '২০২৩'), (2024, '২০২৪'), (2025, '২০২৫')], default=2025, verbose_name='বছর'),
        ),
        migrations.AddConstraint(
            model_name='storage',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'product', 'rate'), name='unique_storage'),
        ),
    ]
