# Generated by Django 5.1.3 on 2024-12-11 16:17

import Transaction.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIncomeExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=Transaction.functions.last_balance_date, verbose_name='তারিখ')),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='বিবরণ')),
                ('amount', models.FloatField(null=True, verbose_name='টাকা')),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenditureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='নাম')),
                ('serial', models.SmallIntegerField(default=1, verbose_name='ক্রম')),
            ],
            options={
                'ordering': ['serial', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='নাম')),
                ('serial', models.SmallIntegerField(default=1, verbose_name='ক্রম')),
            ],
            options={
                'ordering': ['serial', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('baseincomeexpenditure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IncomeExpenditure.baseincomeexpenditure')),
            ],
            bases=('IncomeExpenditure.baseincomeexpenditure',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('baseincomeexpenditure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IncomeExpenditure.baseincomeexpenditure')),
            ],
            bases=('IncomeExpenditure.baseincomeexpenditure',),
        ),
        migrations.AddField(
            model_name='baseincomeexpenditure',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IncomeExpenditure.expendituregroup', verbose_name='খাত'),
        ),
    ]
