# Generated by Django 5.1.3 on 2024-12-18 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncomeExpenditure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseincomeexpenditure',
            name='group',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IncomeExpenditure.expendituregroup', verbose_name='খাত'),
        ),
        migrations.AddField(
            model_name='income',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IncomeExpenditure.incomegroup', verbose_name='খাত'),
        ),
    ]
