# Generated by Django 4.2.3 on 2023-10-16 12:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='নাম')),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='নাম')),
            ],
        ),
        migrations.CreateModel(
            name='LendLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='তারিখ')),
                ('loan_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='হাওলাদের পরিমাণ')),
                ('refund_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='ফেরতের পরিমাণ')),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Loan.borrower', verbose_name='হাওলাদ গ্রহণকারী')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='তারিখ')),
                ('loan_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='হাওলাদের পরিমাণ')),
                ('refund_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='পরিশোধের পরিমাণ')),
                ('lender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Loan.lender', verbose_name='হাওলাদ প্রদানকারী')),
            ],
        ),
    ]
