# Generated by Django 4.2.3 on 2023-10-16 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowloan',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='borrowloan',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='lendloan',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='lendloan',
            name='refund_amount',
        ),
        migrations.AddField(
            model_name='borrowloan',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='হাওলাদের পরিমাণ'),
        ),
        migrations.AddField(
            model_name='borrowloan',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='পরিশোধিত'),
        ),
        migrations.AddField(
            model_name='lendloan',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='হাওলাদের পরিমাণ'),
        ),
        migrations.AddField(
            model_name='lendloan',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='পরিশোধিত'),
        ),
        migrations.CreateModel(
            name='RefundLendedLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='তারিখ')),
                ('amount', models.IntegerField(default=0, verbose_name='ফেরতের পরিমাণ')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loan.lendloan', verbose_name='হাওলাদ')),
            ],
        ),
        migrations.CreateModel(
            name='RefundBorrowedLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='তারিখ')),
                ('amount', models.IntegerField(default=0, verbose_name='পরিশোধের পরিমাণ')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loan.borrowloan', verbose_name='হাওলাদ')),
            ],
        ),
    ]
