# Generated by Django 4.1.3 on 2022-12-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_alter_cashbalance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbalance',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
