# Generated by Django 4.1.3 on 2023-02-06 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_alter_cashbalance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbalance',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='cashbalance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='তারিখ'),
        ),
    ]
