# Generated by Django 4.1.3 on 2023-02-14 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0004_alter_cashbalance_amount_alter_cashbalance_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbalance',
            options={'ordering': ['-date']},
        ),
    ]
