# Generated by Django 4.1.3 on 2023-03-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0005_alter_cashbalance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbalance',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='পরিমাণ'),
        ),
    ]
