# Generated by Django 4.2.3 on 2024-08-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0006_alter_cashbalance_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbalance',
            options={'get_latest_by': ['date'], 'ordering': ['-date']},
        ),
    ]
