# Generated by Django 4.2.3 on 2024-11-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0007_alter_cashbalance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbalance',
            options={'get_latest_by': 'date', 'ordering': ['-date']},
        ),
    ]
