# Generated by Django 4.2.3 on 2024-09-20 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0007_alter_cashbalance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='তারিখ')),
                ('cash', models.IntegerField(default=0, verbose_name='হাতে নগদ')),
                ('bank', models.IntegerField(default=0, verbose_name='ব্যাংক জমা')),
                ('pay_order', models.IntegerField(default=0, verbose_name='পে-অর্ডার')),
                ('due_slip', models.IntegerField(default=0, verbose_name='পে-অর্ডার এর ডিউ স্লিপ')),
            ],
            options={
                'get_latest_by': ['date'],
            },
        ),
    ]
