# Generated by Django 5.1.3 on 2024-11-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0008_alter_cashbalance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbalance',
            name='amount',
            field=models.FloatField(null=True, verbose_name='পরিমাণ'),
        ),
    ]
