# Generated by Django 4.1.3 on 2022-12-03 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('detail', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0.0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revenue.revenuegroup')),
            ],
        ),
    ]
