# Generated by Django 4.1.3 on 2022-12-14 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Revenue', '0002_alter_revenue_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='revenuegroup',
            options={'ordering': ['name']},
        ),
    ]
