# Generated by Django 4.1.3 on 2022-12-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Revenue', '0003_alter_revenue_options_alter_revenuegroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Revenue.revenuegroup'),
        ),
    ]
