# Generated by Django 4.1.3 on 2022-12-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revenue', '0004_alter_revenue_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
