# Generated by Django 4.1.3 on 2023-01-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revenue', '0005_alter_revenue_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuegroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='নাম'),
        ),
    ]
