# Generated by Django 4.1.3 on 2023-01-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Revenue', '0006_alter_revenuegroup_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['-date']},
        ),
    ]
