# Generated by Django 4.1.3 on 2023-02-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revenue', '0008_alter_revenue_amount_alter_revenue_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenuegroup',
            options={'ordering': ['serial', 'name']},
        ),
        migrations.AddField(
            model_name='revenuegroup',
            name='serial',
            field=models.SmallIntegerField(default=1, verbose_name='ক্রম'),
        ),
    ]
