# Generated by Django 4.1.3 on 2023-03-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revenue', '0009_alter_revenuegroup_options_revenuegroup_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='টাকা'),
        ),
    ]
