# Generated by Django 5.1.3 on 2024-11-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revenue', '0010_alter_revenue_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='amount',
            field=models.FloatField(null=True, verbose_name='টাকা'),
        ),
    ]
