# Generated by Django 4.1.3 on 2022-12-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
