# Generated by Django 4.1.3 on 2022-12-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0003_alter_expenditure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Expenditure.expendituregroup'),
        ),
    ]
