# Generated by Django 5.1.3 on 2024-11-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0011_alter_expenditure_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='amount',
            field=models.FloatField(null=True, verbose_name='টাকা'),
        ),
    ]
