# Generated by Django 5.1.3 on 2024-12-11 16:17

import Transaction.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0012_alter_expenditure_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenditure',
            options={'get_latest_by': ['date'], 'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='date',
            field=models.DateField(default=Transaction.functions.last_balance_date, verbose_name='তারিখ'),
        ),
    ]
